/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controller.ControllerProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelProduto;

/**
 *
 * @author igork
 */
public class TelaProduto extends javax.swing.JFrame {

    ArrayList<ModelProduto> listaModelProduto = new ArrayList<>();
    ControllerProduto ControllerProduto = new ControllerProduto();
    ModelProduto modelProduto = new ModelProduto();
    String salvarAlteracao;
    
    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
        setLocationRelativeTo(null);
        carregarProdutos();
        habilitarCampos(false);
        funcoesDoPrograma();
        jbProdutoSalvar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uJPanelImagem1 = new componentes.UJPanelImagem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProdutoTabela = new javax.swing.JTable();
        jtfProdutoValor = new javax.swing.JFormattedTextField();
        jlProdutoValor = new javax.swing.JLabel();
        jtfProdutoEstoque = new javax.swing.JFormattedTextField();
        jlProdutoEstoque = new javax.swing.JLabel();
        jlProdutoTamanho = new javax.swing.JLabel();
        jcProdutoTamanho = new javax.swing.JComboBox<>();
        jtfProdutoCor = new javax.swing.JTextField();
        jtfProdutoMarca = new javax.swing.JTextField();
        jtfProdutoNome = new javax.swing.JTextField();
        jtfProdutoPesquisar = new javax.swing.JTextField();
        jbProdutoPesquisar = new javax.swing.JButton();
        jlProdutoCodigo = new javax.swing.JLabel();
        jtfProdutoCodigo = new javax.swing.JTextField();
        jlProdutoDescricao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbProdutoCancelar = new javax.swing.JButton();
        jbProdutoExcluir = new javax.swing.JButton();
        jbProdutoAlterar = new javax.swing.JButton();
        jbProdutoNovo = new javax.swing.JButton();
        jbProdutoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIADOR DE PRODUTOS");
        setResizable(false);

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\Igor\\OneDrive\\Documentos\\NetBeansProjects\\SoftwareLoyal\\src\\imagens\\loyalstorebranco.png"));

        jtProdutoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Marca", "Cor", "Quantidade ", "Tamanho", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProdutoTabela);
        if (jtProdutoTabela.getColumnModel().getColumnCount() > 0) {
            jtProdutoTabela.getColumnModel().getColumn(0).setMinWidth(5);
            jtProdutoTabela.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtProdutoTabela.getColumnModel().getColumn(1).setMinWidth(100);
            jtProdutoTabela.getColumnModel().getColumn(1).setPreferredWidth(150);
            jtProdutoTabela.getColumnModel().getColumn(2).setMinWidth(70);
            jtProdutoTabela.getColumnModel().getColumn(2).setPreferredWidth(70);
            jtProdutoTabela.getColumnModel().getColumn(3).setMinWidth(85);
            jtProdutoTabela.getColumnModel().getColumn(3).setPreferredWidth(85);
            jtProdutoTabela.getColumnModel().getColumn(4).setMinWidth(40);
            jtProdutoTabela.getColumnModel().getColumn(4).setPreferredWidth(40);
            jtProdutoTabela.getColumnModel().getColumn(5).setMinWidth(25);
            jtProdutoTabela.getColumnModel().getColumn(5).setPreferredWidth(25);
            jtProdutoTabela.getColumnModel().getColumn(6).setMinWidth(20);
            jtProdutoTabela.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        jtfProdutoValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jlProdutoValor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlProdutoValor.setForeground(new java.awt.Color(255, 255, 255));
        jlProdutoValor.setText("Valor:");

        jtfProdutoEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jlProdutoEstoque.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlProdutoEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jlProdutoEstoque.setText("Estoque:");

        jlProdutoTamanho.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlProdutoTamanho.setForeground(new java.awt.Color(255, 255, 255));
        jlProdutoTamanho.setText("Tamanho:");

        jcProdutoTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "M", "G", "GG", "EXG" }));

        jtfProdutoCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProdutoCorActionPerformed(evt);
            }
        });

        jtfProdutoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProdutoMarcaActionPerformed(evt);
            }
        });

        jtfProdutoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProdutoPesquisarActionPerformed(evt);
            }
        });

        jbProdutoPesquisar.setText("Pesquisar");
        jbProdutoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutoPesquisarActionPerformed(evt);
            }
        });

        jlProdutoCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jlProdutoCodigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlProdutoCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jlProdutoCodigo.setText("Código:");

        jtfProdutoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProdutoCodigoActionPerformed(evt);
            }
        });

        jlProdutoDescricao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlProdutoDescricao.setForeground(new java.awt.Color(255, 255, 255));
        jlProdutoDescricao.setText("Descrição:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marca:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cor:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pesquisar descrição");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/de-volta (1).png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbProdutoCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbProdutoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/cancelar (1).png"))); // NOI18N
        jbProdutoCancelar.setText("Cancelar");
        jbProdutoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutoCancelarActionPerformed(evt);
            }
        });

        jbProdutoExcluir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbProdutoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/excluir (1).png"))); // NOI18N
        jbProdutoExcluir.setText("Excluir");
        jbProdutoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutoExcluirActionPerformed(evt);
            }
        });

        jbProdutoAlterar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbProdutoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/lapis (1).png"))); // NOI18N
        jbProdutoAlterar.setText("Alterar");
        jbProdutoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutoAlterarActionPerformed(evt);
            }
        });

        jbProdutoNovo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbProdutoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/novo-documento (1).png"))); // NOI18N
        jbProdutoNovo.setText("Novo");
        jbProdutoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutoNovoActionPerformed(evt);
            }
        });

        jbProdutoSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbProdutoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/salve- (1).png"))); // NOI18N
        jbProdutoSalvar.setText("Salvar");
        jbProdutoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfProdutoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlProdutoCodigo))
                                        .addGap(18, 18, 18)
                                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlProdutoDescricao)
                                            .addComponent(jtfProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                        .addComponent(jtfProdutoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbProdutoPesquisar)))
                                .addGap(18, 18, 18)
                                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfProdutoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(24, 24, 24)
                                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jtfProdutoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                .addComponent(jlProdutoTamanho)
                                .addGap(18, 18, 18)
                                .addComponent(jlProdutoEstoque))
                            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                .addComponent(jcProdutoTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlProdutoValor)
                                    .addComponent(jtfProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfProdutoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jbProdutoCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jbProdutoExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jbProdutoAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbProdutoNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jbProdutoSalvar)))
                .addContainerGap())
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlProdutoDescricao)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jlProdutoTamanho)
                        .addComponent(jlProdutoEstoque))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlProdutoCodigo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfProdutoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfProdutoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfProdutoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcProdutoTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProdutoValor)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfProdutoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbProdutoPesquisar))
                    .addComponent(jtfProdutoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jbProdutoCancelar)
                    .addComponent(jbProdutoExcluir)
                    .addComponent(jbProdutoAlterar)
                    .addComponent(jbProdutoSalvar)
                    .addComponent(jbProdutoNovo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jtfProdutoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProdutoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProdutoCodigoActionPerformed

    private void jtfProdutoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProdutoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProdutoPesquisarActionPerformed

    private void jbProdutoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutoPesquisarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.jtProdutoTabela.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jtProdutoTabela.setRowSorter(classificador);
        String textoPesquisado = jtfProdutoPesquisar.getText();
        classificador.setRowFilter(RowFilter.regexFilter(textoPesquisado.toLowerCase(), 1));
        
    }//GEN-LAST:event_jbProdutoPesquisarActionPerformed
    
    private void salvarProduto(){
        modelProduto.setProduto_nome(this.jtfProdutoNome.getText()); 
        modelProduto.setProduto_marca(this.jtfProdutoMarca.getText()); 
        modelProduto.setProduto_cor(this.jtfProdutoCor.getText()); 
        modelProduto.setProduto_tamanho((String) this.jcProdutoTamanho.getSelectedItem());
        modelProduto.setProduto_estoque(Integer.parseInt(this.jtfProdutoEstoque.getText()));
        modelProduto.setProduto_valor(Double.parseDouble(this.jtfProdutoValor.getText().replace(',', '.')));
        if (ControllerProduto.salvarProdutoController(modelProduto)>0) {
            JOptionPane.showMessageDialog(this, " O produto foi registrado com sucesso.");
            carregarProdutos();
            limparcampos();
            habilitarCampos(false);
            jbProdutoSalvar.setEnabled(false);
            jbProdutoAlterar.setEnabled(true);
            jbProdutoExcluir.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this, " Erro ao registrar o produto.");
        }
    }
    
    private void alterarProduto(){
        modelProduto.setProduto_nome(this.jtfProdutoNome.getText()); 
        modelProduto.setProduto_marca(this.jtfProdutoMarca.getText()); 
        modelProduto.setProduto_cor(this.jtfProdutoCor.getText()); 
        modelProduto.setProduto_tamanho((String) this.jcProdutoTamanho.getSelectedItem());
        modelProduto.setProduto_estoque(Integer.parseInt(this.jtfProdutoEstoque.getText()));
        modelProduto.setProduto_valor(Double.parseDouble(this.jtfProdutoValor.getText()));
        if (ControllerProduto.atualizarProdutoController(modelProduto)) {
            JOptionPane.showMessageDialog(this, " O produto foi alterado com sucesso.");
            carregarProdutos();
            limparcampos();
            habilitarCampos(false);
            
        }else{
            JOptionPane.showMessageDialog(this, " Erro ao alterar o produto.");
        }
    }
    
    private void funcoesDoPrograma(){
        jtfProdutoCodigo.setEnabled(false);
        jtfProdutoCodigo.setToolTipText("Preenchimento automático.");
    }
    private void habilitarCampos(boolean condicao){
        jtfProdutoNome.setEnabled(condicao);
        jtfProdutoMarca.setEnabled(condicao);
        jtfProdutoCor.setEnabled(condicao);
        jtfProdutoEstoque.setEnabled(condicao);
        jtfProdutoValor.setEnabled(condicao);
        jcProdutoTamanho.setEnabled(condicao);
        
    }
    private void limparcampos(){
        jtfProdutoEstoque.setText("");
        jtfProdutoNome.setText("");
        jtfProdutoMarca.setText("");
        jtfProdutoCor.setText("");
        jtfProdutoValor.setText("");
            
    }
    private void jtfProdutoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProdutoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProdutoMarcaActionPerformed

    private void jtfProdutoCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProdutoCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProdutoCorActionPerformed

    private void jbProdutoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutoSalvarActionPerformed
        // TODO add your handling code here:
        jtfProdutoCodigo.setText("");
        if (salvarAlteracao=="salvar") {
            this.salvarProduto();
        }else if(salvarAlteracao=="alterar") {
            this.alterarProduto();
        }

    }//GEN-LAST:event_jbProdutoSalvarActionPerformed

    private void jbProdutoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutoNovoActionPerformed
        // TODO add your handling code here:
        habilitarCampos(true);
        limparcampos();
        salvarAlteracao = "salvar";
        jbProdutoSalvar.setEnabled(true);
        jbProdutoAlterar.setEnabled(false);
        jbProdutoExcluir.setEnabled(false);
    }//GEN-LAST:event_jbProdutoNovoActionPerformed

    private void jbProdutoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutoAlterarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = this.jtProdutoTabela.getSelectedRow();
        salvarAlteracao = "alterar";
        habilitarCampos(true);
        try {
            int codigoProduto = (int) this.jtProdutoTabela.getValueAt(linhaSelecionada, 0);
            modelProduto = ControllerProduto.getProdutoController(codigoProduto);
            this.jtfProdutoCodigo.setText(String.valueOf(modelProduto.getId_produto()));
            this.jtfProdutoNome.setText(modelProduto.getProduto_nome());
            this.jtfProdutoMarca.setText(modelProduto.getProduto_marca());
            this.jtfProdutoCor.setText(modelProduto.getProduto_cor());
            this.jtfProdutoEstoque.setText(String.valueOf(modelProduto.getProduto_estoque()));
            this.jtfProdutoValor.setText(String.valueOf(modelProduto.getProduto_valor()));
            this.jcProdutoTamanho.setSelectedItem(modelProduto.getProduto_tamanho());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Erro ao alterar o produto.");
        }
    }//GEN-LAST:event_jbProdutoAlterarActionPerformed

    private void jbProdutoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutoExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = jtProdutoTabela.getSelectedRow();
        int codigoProduto =(int) jtProdutoTabela.getValueAt(linhaSelecionada, 0);
        if (ControllerProduto.excluirProdutoController(codigoProduto)) {
            JOptionPane.showMessageDialog(this, " O produto foi excluido com sucesso.");
            carregarProdutos();
        }else{
            JOptionPane.showMessageDialog(this, " Erro ao excluir o produto.");
        }

    }//GEN-LAST:event_jbProdutoExcluirActionPerformed

    private void jbProdutoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutoCancelarActionPerformed
        // TODO add your handling code here:
        habilitarCampos(false);
        limparcampos();
        jbProdutoAlterar.setEnabled(true);
        jbProdutoExcluir.setEnabled(true);
        jbProdutoSalvar.setEnabled(false);
    }//GEN-LAST:event_jbProdutoCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
  
    private void carregarProdutos(){
        listaModelProduto = ControllerProduto.getListaProdutoController();
        DefaultTableModel model = (DefaultTableModel) jtProdutoTabela.getModel();
        model.setNumRows(0); 
        int contador = listaModelProduto.size();
        for (int i = 0; i < contador; i++) {
            model.addRow(new Object[]{
                listaModelProduto.get(i).getId_produto(),
                listaModelProduto.get(i).getProduto_nome(),  
                listaModelProduto.get(i).getProduto_marca(),  
                listaModelProduto.get(i).getProduto_cor(),  
                listaModelProduto.get(i).getProduto_estoque(),
                listaModelProduto.get(i).getProduto_tamanho(),
                listaModelProduto.get(i).getProduto_valor()
            });
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbProdutoAlterar;
    private javax.swing.JButton jbProdutoCancelar;
    private javax.swing.JButton jbProdutoExcluir;
    private javax.swing.JButton jbProdutoNovo;
    private javax.swing.JButton jbProdutoPesquisar;
    private javax.swing.JButton jbProdutoSalvar;
    private javax.swing.JComboBox<String> jcProdutoTamanho;
    private javax.swing.JLabel jlProdutoCodigo;
    private javax.swing.JLabel jlProdutoDescricao;
    private javax.swing.JLabel jlProdutoEstoque;
    private javax.swing.JLabel jlProdutoTamanho;
    private javax.swing.JLabel jlProdutoValor;
    private javax.swing.JTable jtProdutoTabela;
    private javax.swing.JTextField jtfProdutoCodigo;
    private javax.swing.JTextField jtfProdutoCor;
    private javax.swing.JFormattedTextField jtfProdutoEstoque;
    private javax.swing.JTextField jtfProdutoMarca;
    private javax.swing.JTextField jtfProdutoNome;
    private javax.swing.JTextField jtfProdutoPesquisar;
    private javax.swing.JFormattedTextField jtfProdutoValor;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
}
